version: "3.9"
services:
  zlmediakit:
    image: zlmediakit/zlmediakit:master
    container_name: zlmediakit
    ports:
      - "1935:1935"       # RTMP
      - "8080:80"         # HTTP
      - "8443:443"        # HTTPS
      - "8554:554"        # RTSP
      - "10000:10000"     # RTP (TCP)
      - "10000:10000/udp" # RTP (UDP)
      - "8000:8000/udp"   # 其他 UDP 服务
      - "9000:9000/udp"   # 其他 UDP 服务
    volumes:
      - ./zlmediakit/conf/config.ini:/opt/media/conf/config.ini  # 挂载自定义配置文件
    environment:
      TZ: "Asia/Shanghai"  # 设置时区
    restart: "on-failure:3"  # 重启策略
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
#nginx配置
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - webnet

  networks:
    webnet: